package test

import "core:fmt"
import "core:log"
import "json:read"

// sample.json was taken from Wikipedia
// suzanne.gltf was generated by blender and exported to gltf 2.0
main :: proc() {
    context.logger = log.create_console_logger();
    if json, ok := read.read_from_path("sample.json"); ok {
        fmt.println(json);
    }
}
